# Generated by Django 5.1.6 on 2025-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('guessed_letters', models.CharField(blank=True, max_length=100)),
                ('correct_guesses', models.IntegerField(default=0)),
                ('total_guesses', models.IntegerField(default=0)),
            ],
        ),
    ]
